hotfix: 서버 CD - CheckStyle 해제

diff --git a/.github/workflows/deploy-server.yml b/.github/workflows/deploy-server.yml
--- a/.github/workflows/deploy-server.yml
+++ b/.github/workflows/deploy-server.yml
@@ -17,12 +17,12 @@ jobs:
           java-version: '17'
           distribution: "adopt"
 
-      - name: Clean Gradle Build (Skip Tests)
+      - name: Clean Gradle Build (Skip Tests & Checkstyle)
         run: |
           cd backend
           chmod +x ./gradlew
           ./gradlew clean --no-daemon
-          ./gradlew build -x test -x compileTestJava -x checkstyleMain --no-daemon
+          ./gradlew build -x test -x compileTestJava -x checkstyleMain -x editorconfigCheck -x checkstyleTest --no-daemon
 
       - name: Docker build & push
         run: |
@@ -32,15 +32,21 @@ jobs:
 
       - name: Get GitHub Actions Runner IP
         run: |
-          echo "RUNNER_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV
+          RUNNER_IP=$(curl -s ifconfig.me)
+          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
           echo "GitHub Actions Runner IP: $RUNNER_IP"
 
       - name: Add SSH IP to EC2 Security Group
         run: |
-          aws ec2 authorize-security-group-ingress \
-            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
-            --protocol tcp --port 22 --cidr $RUNNER_IP/32 \
-            --region ${{ secrets.AWS_REGION }}
+          if [[ -n "$RUNNER_IP" ]]; then
+            aws ec2 authorize-security-group-ingress \
+              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+              --protocol tcp --port 22 --cidr $RUNNER_IP/32 \
+              --region ${{ secrets.AWS_REGION }}
+          else
+            echo "Error: RUNNER_IP is empty"
+            exit 1
+          fi
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -86,10 +92,15 @@ jobs:
       - name: Remove SSH IP from Security Group
         if: always()
         run: |
-          aws ec2 revoke-security-group-ingress \
-            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
-            --protocol tcp --port 22 --cidr $RUNNER_IP/32 \
-            --region ${{ secrets.AWS_REGION }}
+          if [[ -n "$RUNNER_IP" ]]; then
+            aws ec2 revoke-security-group-ingress \
+              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
+              --protocol tcp --port 22 --cidr $RUNNER_IP/32 \
+              --region ${{ secrets.AWS_REGION }}
+          else
+            echo "Error: RUNNER_IP is empty"
+            exit 1
+          fi
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
